apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"captureorder","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"captureorder"}},"template":{"metadata":{"labels":{"app":"captureorder"}},"spec":{"containers":[{"env":[{"name":"MONGOHOST","valueFrom":{"secretKeyRef":{"key":"mongoHost","name":"mongodb"}}},{"name":"MONGOUSER","valueFrom":{"secretKeyRef":{"key":"mongoUser","name":"mongodb"}}},{"name":"MONGOPASSWORD","valueFrom":{"secretKeyRef":{"key":"mongoPassword","name":"mongodb"}}}],"image":"azch/captureorder","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/healthz","port":8080}},"name":"captureorder","ports":[{"containerPort":8080}],"readinessProbe":{"httpGet":{"path":"/healthz","port":8080}},"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2020-02-25T11:44:43Z"
  generation: 6
  name: captureorder
  resourceVersion: "5044548"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/captureorder
  uid: 54778b30-5135-47ad-8970-ee2bf11b2b56
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: captureorder
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: captureorder
    spec:
      containers:
      - env:
        - name: MONGOHOST
          valueFrom:
            secretKeyRef:
              key: mongoHost
              name: mongodb
        - name: MONGOUSER
          valueFrom:
            secretKeyRef:
              key: mongoUser
              name: mongodb
        - name: MONGOPASSWORD
          valueFrom:
            secretKeyRef:
              key: mongoPassword
              name: mongodb
        image: azch/captureorder
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: captureorder
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
